name: Scheduled RSS Backup to B2

on:
  schedule:
    # LÃ¤uft alle 6 Stunden (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Erlaubt es dir, den Lauf auch jederzeit manuell zu starten

jobs:
  backup:
    runs-on: ubuntu-latest
    concurrency:
      group: backup-group
      cancel-in-progress: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 lxml markdownify b2sdk feedparser

      - name: Run Backup Script
        env:
          B2_KEY_ID: ${{ secrets.B2_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
          B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
        run: python backup/regular_backup.py # add name of regular backup script

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update posted.txt [skip ci]"
          file_pattern: 'posted.txt'